name: Deploy to ec2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ubuntu
          SERVER_HOST: 65.1.100.43
        run: |
          # Add SSH key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

          # Connect to server and deploy
          ssh $SERVER_USER@$SERVER_HOST << 'EOF'
            cd ~/my-portfolio
            git pull origin main
            npm install --production
            npm run build
            pm2 restart portfolio --no-watch
          EOF
